services:
  elasticsearch:
    image: elasticsearch:8.17.2
    container_name: elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - discovery.type=single-node
      - ELASTICSEARCH_PASSWORD=admin1234 # elastic 用户密码相同
    volumes:
      - D:/Project/毕业设计/InfoQuest-Node/backend/data/elasticsearch/data:/usr/share/elasticsearch/data
      - D:/Project/毕业设计/InfoQuest-Node/backend/data/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - D:/Project/毕业设计/InfoQuest-Node/backend/data/elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    privileged: true
    networks:
      - elastic-net
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: kibana:8.17.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - D:/Project/毕业设计/InfoQuest-Node/backend/data/kibana/data:/usr/share/kibana/data
      - D:/Project/毕业设计/InfoQuest-Node/backend/data/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - elastic-net
    ports:
      - "5601:5601"

networks:
  elastic-net:
    driver: bridge
